# Generated by Django 4.2.5 on 2023-11-24 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id_alergia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_alergia', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('rut_contacto_emergencia', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('es_usuario_app', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(default='2023-11-24')),
            ],
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id_discapacidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_discapacidad', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id_enfermedad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_enfermedad', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_medicamento', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut_usuario', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('apellido_usuario', models.CharField(max_length=100)),
                ('correo_usuario', models.EmailField(max_length=100)),
                ('contrasenia_usuario', models.CharField(max_length=250)),
                ('direccion_usuario', models.CharField(max_length=250)),
                ('telefono_usuario', models.IntegerField()),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro'), ('N', 'Prefiero no decirlo')], default='N', max_length=1)),
                ('foto_de_perfil', models.ImageField(blank=True, null=True, upload_to='perfil/')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_inicio_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio_sesion', models.DateField(max_length=100)),
                ('hora_inicio_sesion', models.CharField(max_length=100)),
                ('ubicacion_inicio_sesion', models.CharField(max_length=100)),
                ('id_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeDeAlerta',
            fields=[
                ('id_mensaje_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje_alerta', models.CharField(max_length=100)),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Marcador',
            fields=[
                ('id_marcador', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('mensade_de_alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.mensajedealerta')),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionDeSalud',
            fields=[
                ('id_info_salud', models.AutoField(primary_key=True, serialize=False)),
                ('altura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('hora_evento', models.CharField(max_length=100)),
                ('fecha_evento', models.DateField(max_length=100)),
                ('ubicacion_evento', models.CharField(max_length=100)),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='rut_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario'),
        ),
        migrations.CreateModel(
            name='DetalleMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_medicamento', models.BooleanField()),
                ('id_info_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.informaciondesalud')),
                ('id_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.medicamento')),
            ],
            options={
                'unique_together': {('id_medicamento', 'id_info_salud')},
            },
        ),
        migrations.CreateModel(
            name='DetalleEnfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_enfermedad', models.BooleanField()),
                ('id_enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.enfermedad')),
                ('id_info_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.informaciondesalud')),
            ],
            options={
                'unique_together': {('id_enfermedad', 'id_info_salud')},
            },
        ),
        migrations.CreateModel(
            name='DetalleDiscapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_discapacidad', models.BooleanField()),
                ('id_discapacidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.discapacidad')),
                ('id_info_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.informaciondesalud')),
            ],
            options={
                'unique_together': {('id_discapacidad', 'id_info_salud')},
            },
        ),
        migrations.CreateModel(
            name='DetalleContactoEmergencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_adicion', models.DateField(max_length=100)),
                ('rut_contacto_emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.contactoemergencia')),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario')),
            ],
            options={
                'unique_together': {('rut_usuario', 'rut_contacto_emergencia')},
            },
        ),
        migrations.CreateModel(
            name='DetalleAlergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_alergia', models.BooleanField()),
                ('id_alergia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.alergia')),
                ('id_info_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.informaciondesalud')),
            ],
            options={
                'unique_together': {('id_alergia', 'id_info_salud')},
            },
        ),
    ]
