# Generated by Django 4.2.5 on 2023-11-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_cuenta_fecha_creacion_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='fecha_creacion',
            field=models.DateField(default='2023-11-28'),
        ),
    ]
