# Generated by Django 4.2.5 on 2023-11-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_cuenta_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='fecha_creacion',
            field=models.DateField(default='2023-11-30'),
        ),
    ]
