# Generated by Django 4.2.5 on 2023-12-02 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_cuenta_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='estado_cuenta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fecha_creacion',
            field=models.DateField(default='2023-12-01'),
        ),
        migrations.CreateModel(
            name='ActivateAccountToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_aat', models.CharField(max_length=255)),
                ('fecha_expiracion_aat', models.DateTimeField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario')),
            ],
        ),
    ]
