# Generated by Django 4.2.5 on 2023-12-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_cuenta_estado_cuenta_alter_cuenta_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='fecha_creacion',
            field=models.DateField(default='2023-12-03'),
        ),
    ]
